name: Test auto-update citation.cff

on:
  workflow_dispatch:


jobs:
  update:
    name: Update version number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: |
          echo "RELEASE_DATE=& Get-Date -format yyyy-MM-dd" >> $GITHUB_ENV
          echo "the release date is ${RELEASE_DATE}"
      - name: edit version number
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'CITATION.cff'
          branch: feature/update-cff
          targetBranch: feature/update-cff
          createPR: false
          commitChange: true
          message: 'updated CITATION.cff'
          changes: |
            {
              "version": "1.0.6",
              "date-released": "${RELEASE_DATE}"
            }