name: Test auto-update citation.cff

on:
  workflow_dispatch:


jobs:
  update:
    name: Update version number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"
      - name: Test time
        run: |
          echo "${{ steps.date.outputs.time }}"
      - name: update version number
        uses: mikefarah/yq@master
        with:
          cmd: yq --inplace '.version = "1.0.13"' CITATION.cff
      - name: update release date
        uses: mikefarah/yq@master
        with:
          cmd: yq --inplace '.date-released = "${{ steps.date.outputs.time }}"' CITATION.cff
      - name: Commit changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_message: "Updated CITATION.cff"
