name: Test auto-update citation.cff

on:
  workflow_dispatch:


jobs:
  update:
    name: Update version number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"
      - name: Test time
        run: |
          echo "${{ steps.date.outputs.time }}"
      - name: edit version number
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'CITATION.cff'
          propertyPath: 'title'
          value: "!${{ steps.date.outputs.time }}"
          branch: feature/update-cff
          targetBranch: feature/update-cff
          createPR: false
          commitChange: true
          message: 'updated version number in CITATION.cff'
          changes: |
            {
              "version": "1.0.8"
            }
