name: Test auto-update citation.cff

on:
  workflow_dispatch:


jobs:
  update:
    name: Update version number
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: edit version number
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'CITATION.cff'
          branch: feature/update-cff
          targetBranch: feature/update-cff
          createPR: true
          commitChange: true
          message: 'updated CITATION.cff'
          changes: |
            {
              "version": "1.0.4"
            }