name: Test auto-update citation.cff

on:
  workflow_dispatch:


jobs:
  update:
    name: Update version number
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: edit version number
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: './CITATION.cff'
          branch: feature/update-cff
          targetBranch: feature/update-cff
          createPR: 'true'
          message: 'changing version'
          changes: |
            {
              "version": 1.0.3
            }
      - name: commit changes
        uses: devops-infra/action-commit-push@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: updated CITATION.cff